### ISSUE TITLE
Can't use structure chain for instance creation

### ISSUE THREAD

**Issue by Timbals** [Ralith/openxrs#77]
The `next` structure chain pointer is currently harcoded to be a nullptr when creating a new instance.

This prevents usage of the extension structures provided by [XR_EXT_debug_utils] (as specified in "Example 1" [here]) and [XR_KHR_android_create_instance].

https://github.com/Ralith/openxrs/blob/5283daa09ddbe7170069ff3ea9e42e8a8a9ff4bc/openxr/src/entry.rs#L144-L159

[XR_EXT_debug_utils]: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrDebugUtilsMessengerCreateInfoEXT
[XR_KHR_android_create_instance]: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrInstanceCreateInfoAndroidKHR
[here]: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_debug_utils

**Comment by Ralith** [comment]
The limited scope of `Entry::create_instance` is by design. It's impossible to define a safe interface to open-ended extension. If you need something that's not covered, you can use `Entry::fp` to get the raw function pointer and invoke it (unsafely) with whatever parameters you like, then wrap the result back up with `Instance::from_raw`.

I'm also open to extending the API with safe wrappers for widely-useful extensions. An `Entry::create_android_instance` would be welcome, for example.

**Comment by Timbals** [comment]
You're right.

I tinkered around a bit and wasn't able to cleanly integrate the functionality to the `Entry` API.
The safe wrappers of extensions should probably provide their own `create_instance` function instead of changing the `Entry`.
I might contribute a safe wrapper for the [XR_EXT_debug_utils] extension soon.
I'm closing the issue.

[XR_EXT_debug_utils]: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_debug_utils
